server:
  port: 9088
spring:
  application:
    name: cloud-turbine-dashboard
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
turbine:
  appConfig: cloud-order-service,cloud-goods-service
  clusterNameExpression: "'default'"